export const CREATE_MOVIE = "CREATE_MOVIE";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_ERROR = "CREATE_MOVIE_ERROR";

export const GET_GENRES = "GET_GENRES";
export const SET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_ERROR = "GET_GENRES_ERROR";

export const GET_MOVIES = "GET_MOVIES";
export const SET_MOVIES_SUCCESS = "SET_MOVIES_SUCCESS";
export const GET_MOVIES_ERROR = "GET_MOVIES_ERROR";

export const GET_MOVIE = "GET_MOVIE";
export const SET_MOVIE_SUCCESS = "SET_MOVIE_SUCCESS";
export const GET_MOVIE_ERROR = "GET_MOVIE_ERROR";
