export const CREATE_MOVIE = "CREATE_MOVIE"
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS"
export const CREATE_MOVIE_ERROR = "CREATE_MOVIE_ERROR"

export const LOAD_GENRES = "GET_GENRES"
export const LOAD_GENRES_SUCCESS = "GET_GENRES_SUCCESS"
export const LOAD_GENRES_ERROR = "GET_GENRES_ERROR"